### ISSUE TITLE
Bug with custom attributes when translating to DocBook

### ISSUE THREAD

**Issue by pela9** [riboseinc/asciidoctor-bibliography#101]
Thanks for all your fixes. I've noticed a strange bug when using asciiidoctor-bibliography to convert to DocBook. The following works fine:

    :bibliography-database: refs.bib
    :bibliography-style: ieee
    ...
    Look for further information in the GNU Make manual cite:[GMAKE].
    Some text.
    #Some highlighted text.#

But if I replace the last line with:

    [.sb]#Some text in semibold#.

Asciidoctor-bibliography gets confused, the DocBook output is:

    <simpara>Look for further information in the GNU Make manual <link 
    linkend="bibliography-default-GMAKE"><phrase role="1&rsqb;</link>.
    Some text.
    [.sb">Some text in semibold.</phrase></simpara>"""

**Comment by pela9** [comment]
Sorry for some minor misspellings above, it shall be

    [.sb]#Some text in semibold.#

And there are no triple quotes last in the translation.

**Comment by paolobrasolin** [comment]
@pela9 Thanks for the report!
I confirm this is a bug. I'm working on it in #103.

**Comment by paolobrasolin** [comment]
@pela9 `v0.10.2` was just released to solve the issue.
Thanks for your detailed report!
