### ISSUE TITLE
Question: own styles

### ISSUE THREAD

**Issue by pddzaic** [riboseinc/asciidoctor-bibliography#102]
EDIT: Please delete this issue. Everything works as expected. Sorry !!!!

------

Unfortunately, I don't know where to place my question, so I'll place it here once.

There is the possibility to define your own styles. Suppose I have generated a style "test.csl" and it is located in the same directory as my adoc-file.

The following code does not work:

```
= My first document using asciidoctor-bibliography
:bibliography-database: test.bib
:bibliography-style: test.csl
```

Compiling leads to:

`
asciidoctor: FAILED: C:/test/test.adoc: Failed to load AsciiDoc document - no CSL node: nil
`

How do I integrate these own styles?

**Comment by paolobrasolin** [comment]
No problem, @pddzaic. 😄 

Thanks for using the gem. Feel free to let us know if you find any problems.
