### ISSUE TITLE
Parameterize and i18n "page", "chapter", "section" named attributes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-bibliography#13]

**Comment by paolobrasolin** [comment]
Do you mean that the rendering of the locators should be localized, or that one could use both "chapter" and "chapitre" as an option? The former case is now taken care of by CSL (but not using the TeX-like macro renderer).

**Comment by ronaldtse** [comment]
Yes indeed, the rendering should be localized 👍  If it's already done feel free to close this!
