### ISSUE TITLE
Provide more "Citation Key" styles

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-bibliography#20]
Currently we only support "numbers" and "authoryear" citation styles:

```
:bibliography-citation-style: numbers
```

We should support more "citation key" styles. The CSL library already provides multiple styles we could use:

* "[HiNJ16]" from DIN 1505-2 (alphanumeric, German)
* "[3]" the numeric style
* "AuthorLastName (YEAR)" `authoryear`, etc.

**Comment by paolobrasolin** [comment]
All CSL styles are now supported.
Some need metadata (`citation-label`, `citation-number`) thatn may be missing in some databases. An improvement would be to have a switch to fill it out in the (few) standard ways.

**Comment by ronaldtse** [comment]
@paolobrasolin could you help document the allowed options in the README then? Thanks!

**Comment by paolobrasolin** [comment]
CSL styles are now fully supported. Basic traditional TeX styles are too. Both are documented. (branch `citations`).

**Comment by ronaldtse** [comment]
Close due to #39?

**Comment by paolobrasolin** [comment]
Closing. We'll use #38 to plan more custom styles the TeX macros might need.
