### ISSUE TITLE
Missing bibliography item in BibTeX file caused mysterious error

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-bibliography#33]
When I cite an item that isn't in the database file, the gem throws a "nil cannot be converted to string" error. 

What happens is actually the "find" method is unable to find the item, then the immediate subsequent code assumes the return is a string instead of nil. 

I think we should offer proper StandardError classes for expected errors, such as BibItemNotFoundInDatabase, to directly tell the user what is missing and how to fix it.

There are many places in our code where "success" is assumed. We need to implement better resilience.

**Comment by paolobrasolin** [comment]
Specific error will be solved by PR of branch citations.
In general, more care is taken about resilience.

**Comment by ronaldtse** [comment]
Sounds good. Should this be closed now due to #38?

**Comment by paolobrasolin** [comment]
Yes. Closing.
