### ISSUE TITLE
Implement native :adoc format for Citeproc

### ISSUE THREAD

**Issue by paolobrasolin** [riboseinc/asciidoctor-bibliography#37]
This should be pretty cheap and would assure all styles are rendered correctly and directly in the correct format (instead of regexping our way around html a posteriori).

**Comment by ronaldtse** [comment]
@paolobrasolin I'm not entirely sure what it means...

Are you saying that we should:
* create a new `AsciiCite` format
* create a `AsciiCite` to CSL converter

?

**Comment by paolobrasolin** [comment]
Sorry for lack of clarity. Citeproc (the engine applying CSL styles to bibliographical data) uses Formats. That is, simple classes that render basic style elements (bold, italis, smallcaps, etc) in a format-aware way (plain text, html).

See http://www.rubydoc.info/gems/citeproc-ruby/CiteProc/Ruby/Formats/Html
This is the one we're currently using. After rendering we're regexping our way from html to adoc.

A "native" adoc Format would be a cleaner solution. Not high priority but nice to have.
