### ISSUE TITLE
Better TeX macros

### ISSUE THREAD

**Issue by paolobrasolin** [riboseinc/asciidoctor-bibliography#38]
One first improvement would be to allow for a `bibpunct` option in header that allows the full range of styling one is used to.

A second step is to allow a complete analogy to TeX syntax.
On one hand, it'd be nice to have automatically defined locators (making them localizable is not trivial), on the other hand a user coming from the TeX world is more or less accustomed to inputting an arbitrary string, like in `\cite[prefix][postfix]{key}`.
I feel that in the short term getting the prefix/postifix working would have the highest payoff. And maybe then the parser could treat pure lists of numbers as page ranges as an (optional) shortcut (as some LaTeX packages do).

Also, there's the possibility to simply implement the TeX citation styles as CSL styles themselves and not write any custom code.

Just some food for thought. Do you think custom locators should have higher riority than prefix/suffix? @ronaldtse

**Comment by ronaldtse** [comment]
@paolobrasolin agree on both that we should allow a full analogy to TeX syntax. Prefix and suffix should be an easy and immediate win, that we should do now.

We could also go the CSL route so we can implement the styles there. Feel free to suggest.
