### ISSUE TITLE
bibliography-database location

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-bibliography#52]
The execution of asciidoctor currently assumes that the bibliography-database is in the current directory where the executable is run. Consistent with how asciidoctor works, the bibliography-database should be assumed to be in the same directory as the asciidoc file.

So:

```
./bin/asciidoctor-rfc2 --trace -r asciidoctor-bibliography spec/examples/rfc6350.adoc
```

Is expecting to find rfc6350.bib in ./ . It should in fact expect to find it in spec/examples/ .

**Comment by ronaldtse** [comment]
@opoudjis fully agree. @paolobrasolin could you help with this? Thanks!

**Comment by paolobrasolin** [comment]
@ronaldtse @opoudjis Will do.
