### ISSUE TITLE
Default style

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-bibliography#53]
The current default style is APA. But the style we want for inline citations is the reference abbreviation in brackets; so the inline citation of RFC5322 should be in fact `[RFC5322]`, not `(Resnick, 2008)`. Is there such a reference style in CSL? If not, can we make one? I'm nervous about APA-style citations making it into RFC XML.

**Comment by ronaldtse** [comment]
@opoudjis yes we would need a separate CSL style to render in RFCXML. @paolobrasolin could probably help with the PR to the https://github.com/citation-style-language/styles repo.

**Comment by paolobrasolin** [comment]
@opoudjis This is strictly related to #54 and #56, so this will be solved along with them.

@ronaldtse Would it make sense to have no default style and always require an explicit one? Might avoid some minor confusion for users.

**Comment by ronaldtse** [comment]
@paolobrasolin I think we should always have a default style, but as mentioned here, we probably should print it out in the output like this to prevent confusion?

```
WARNING: asciidoctor-bibliography using default bibliographic style: APA; set ":bibliography-reference-style: apa" or your CSL style to hide this warning
```

And for `doctype: rfc` we can use the [RFC1234] style by default.

**Comment by opoudjis** [comment]
@paolobrasolin : if asciidoctor-bibliography will only ever be used in the context of asciidoctor-rfc, then only the RFC output style is relevant. I don't know whether it is or not; @ronaldtse hints that it isn't.

**Comment by ronaldtse** [comment]
@opoudjis asciidoctor-bibliography is already used in other cases outside asciidoctor-rfc, we simply want it to support asciidoctor-rfc as well.
