### ISSUE TITLE
Citations in v3 are producing spurious relrefs

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-bibliography#61]
In v3, `cite:info[RFC2119]` is supposed to render as `<xref target="RFC2119"/>`; it is ending up rendering incorrectly as `<relref target="RFC2119"/>`.

As far as I can tell, that's occurring inside the gem: it happens when I run it just as `asciidoctor -r asciidoctor-bibliography refs-v3.adoc`

The problem is that in v3, there is differential  output depending on the format of what is contained in the added text: a relref is indeed expected if the Asciidoc crossreference is of format `<<id,\S+ (of|comma|parens|bare)(: )?(.*)$/`, with attributes extracted by `inline_anchor_xref()`

Does the asciidoctor-bibliography gem have to replicate the work of `inline_anchor_xref()`, or can it output an Asciidoc `<<x,y>>` reference, which can then be processed by `inline_anchor_xref()`?

**Comment by opoudjis** [comment]
I tried to do this myself, and didn't get very far.

````
<group delimiter=" " prefix="&lt;&lt;" suffix="&gt;&gt;">
        <text variable="citation-label" prefix="" suffix=""/>
````

works on the rspec of asciidoctor-bibliography and generates `<<ref>>`, but I couldn't get it to propagate into my call of asciidoctor-rfc2, so I couldn't tell whether it would be processed as is by that gem. :-(

**Comment by opoudjis** [comment]
It occurs to me that overloading the cite macro contents may be overkill; a relref can be indicated by passing a "section" attribute to the macro, just as a "format" attribute can be passed to the macro.

**Comment by paolobrasolin** [comment]
I fixed the "simple citation" bug (changing the tag name) in #62.
However the CSL style isn't really the place to implement this logic (has decent logic control but it's too structured). I also feel that neither `asciidoctor-bibliography` is (outside of domain).

However with #63 we should now have enough flexibility to do whatever we want.
Btw, given we're using `<<..>>` interpolations it doesn't make much sense to force some custom syntax (the user will never see) on `asciidoctor-bibliography` macros.

Continuing the discussion on #63.

**Comment by opoudjis** [comment]
Btw, the correct behaviour is in rfc-v3.csl not rfc-v2.csl : the default citation needs to be `<xref/>` not `<xref>[citation]</xref>` in order for it to play well with xml2rfc. Am commenting out rfc-v2.csl code.

**Comment by opoudjis** [comment]
... actually, not even that. The correct behaviour for v3 would be:

````
  it "formats a single citation" do
    expect(formatted_citation("cite:[RFC2119]", options: options)).
      to eq '+++<xref target="RFC2119"/>+++'
  end

  it "formats a single citation with locator" do
    expect(formatted_citation("cite:[RFC2119, section=1.2.3]", options: options)).
      to eq '+++<relref target="RFC2119" section="1.2.3"/>+++'
  end
````

And from what I gather, we've given up on that; CSL is just not that powerful. So not even the locator behaviour is desirable; we'll be using text attributes instead throughout, with raw XML. Again, not happy with that solution, but so long as we're relying on CSL, we're stuck with it.

**Comment by paolobrasolin** [comment]
Unfortunately while CSL/Citeproc (= styling/structuring) cover most common publishing needs they are respectively awkward in rendering code and not arbitrarily extensible.

They were chosen because of their wide adoption (= huge high quality style database) and because the project is a moral heir of `asciidoctor-bibtex`.

I think the only way to cleanly handle the situation would be to define a new pair of styling/structuring standards that encompass all we need. However the scope/effort for such a task would be pretty big. (@ronaldtse possibly too much?)

@opoudjis Thanks for the last commit. Even if the solution isn't perfect, would it make sense to you to release it as a bugfix and close this issue?

**Comment by ronaldtse** [comment]
I've been actually talking to @opoudjis that there should be a better data model for handling bibliographic items and references to documents, and also their formatting into text/syntax.

Let's resolve with a bugfix for now and see how else we can streamline the processing?

**Comment by opoudjis** [comment]
Agreed, Paolo.

**Comment by ronaldtse** [comment]
Since @opoudjis pinged me on this, I think the next thing is to adopt the new bibliography data model in https://github.com/riboseinc/isodoc-models .

@paolobrasolin what's your plan?

**Comment by ronaldtse** [comment]
Closing and moving to new issue #69.
