### ISSUE TITLE
An empty cite:[] is being read in the commented block and it stops

### ISSUE THREAD

**Issue by shahryareiv** [riboseinc/asciidoctor-bibliography#75]
If there is an empty citation `cite:[]`, even in a commented block, it stops and alarms: "Failed to load AsciiDoc document - No entry with id '' was found in the bibliographic database". There are two things to consider:
1- A comment block is comment and should not be converted
2-It is common to put an empty citation `cite:[]` to fill in later. In latex those empty citations `\cite{}` are translated to `??` so the user would see them later in the text.

**Comment by ronaldtse** [comment]
@shahryareiv thanks for the report. The error occurring in a comment certainly makes it a bug.

On the other hand, I agree that empty citations can be filled in later, so we should make this an enhancement in addition to fixing the above.

@paolobrasolin would you have time for this? Thanks!

**Comment by paolobrasolin** [comment]
Solved by #80 and merged in v0.9.0.
Thanks for the report @shahryareiv
