### ISSUE TITLE
Multi-Citation of more than two keys not working

### ISSUE THREAD

**Issue by Fiech** [riboseinc/asciidoctor-bibliography#92]
If more than two citations are used in a multi-citation, only the first and the last elements are used:

**foo.adoc:**
```asciidoc
= Test
:bibliography-database: bibliography.bib

== Chapter

cite:[keyA]+[keyB]+[keyC]+[keyD]

== Bibliography

bibliography::[]
```

**bibliography.bib:**
```asciidoc
@book{keyA,
  title = {Title A},
  author = {Author A},
  year = {2015},
}

@book{keyB,
  title = {Title B},
  author = {Author B},
  year = {2016},
}

@book{keyC,
  title = {Title C},
  author = {Author C},
  year = {2017},
}

@book{keyD,
  title = {Title D},
  author = {Author D},
  year = {2018},
}

```

**command:**
```
asciidoctor -r asciidoctor-bibliography foo.adoc
```

**output:**
![output](https://user-images.githubusercontent.com/7039866/57885835-2370cd00-782c-11e9-8add-ec43481932d9.png)

Tested with the HEAD of this repo, asciidoctor 1.5.8 and 2.0.10dev (from the repo)

**Comment by ronaldtse** [comment]
@Fiech thanks for reporting this -- it sounds like a parsing issue.

@paolobrasolin do you have time to look at this?

**Comment by paolobrasolin** [comment]
@Fiech thanks for the excellent report!

I found and fixed the bug in #93 @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @paolobrasolin ! It’s merged now. 

@Fiech could you let us know if you can confirm the fix? Thanks!

**Comment by Fiech** [comment]
@paolobrasolin @ronaldtse 
Awesome! In my MNWE as well in my actual document this works perfectly. Thank you for the quick fix!

**Comment by ronaldtse** [comment]
That’s great! Sounds like a gem release should be on the way...
