### ISSUE TITLE
[enhancement] nocite macro for bibliography entry without expicit citation

### ISSUE THREAD

**Issue by Fiech** [riboseinc/asciidoctor-bibliography#94]
Similar to the bibtex \nocite{*} command, I propose a nocite:[..] macro to include entries in the bibliography without explicitly citing them.

I openend a pull request #90 that implements that although I do not claim this would be the best way to do this.

**Comment by paolobrasolin** [comment]
This new feature was just released as `0.10.0`. Thanks again for your contribution @Fiech!

cc @ronaldtse
